# Generated by Django 4.1.7 on 2023-03-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
