# Generated by Django 4.1.7 on 2023-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_altura_user_email_user_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peso',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=4),
            preserve_default=False,
        ),
    ]
