# Generated by Django 4.1.7 on 2023-03-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_peso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='endereco',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='altura',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='peso',
            new_name='weight',
        ),
    ]
