# Generated by Django 4.1.7 on 2023-03-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_endereco_user_adress_rename_idade_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('arms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chest', models.DecimalField(decimal_places=1, max_digits=4)),
                ('waist', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hips', models.DecimalField(decimal_places=1, max_digits=4)),
                ('legs', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
