# Generated by Django 4.1.7 on 2023-03-21 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurements',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='users.user'),
            preserve_default=False,
        ),
    ]
