# Generated by Django 4.1.7 on 2023-03-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_nivel_treino_user_nivel_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_treino',
            name='intensidade',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='user',
            name='nivel_treino',
        ),
        migrations.AddField(
            model_name='user',
            name='nivel_treino',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.nivel_treino'),
            preserve_default=False,
        ),
    ]
