# Generated by Django 4.1.7 on 2023-03-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_nivel_treino_intensidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nivel_treino',
            new_name='Training_level',
        ),
        migrations.RenameField(
            model_name='training_level',
            old_name='intensidade',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nivel_treino',
            new_name='training_level',
        ),
    ]
