# Generated by Django 4.1.7 on 2023-03-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_date_onf_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_onf_birth',
            new_name='date_of_birth',
        ),
    ]
