# Generated by Django 4.1.7 on 2023-03-28 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_date_onf_birth_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='date_register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='arms',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='chest',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='hips',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='legs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='waist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
