# Generated by Django 4.1.7 on 2023-03-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_measurements_date_register_alter_measurements_arms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
    ]
