# Generated by Django 4.1.7 on 2023-08-31 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_user_training_level_delete_training_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='body_pictures',
            field=models.ImageField(blank=True, upload_to='users_pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='chest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hips',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='legs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='waist',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
    ]
